"""Domain-level performance analysis for LECSEG-30.

This script aggregates per-video metrics by academic domain for the stable
baseline, the cross-model method, and the balanced method selector. The goal is
to make domain variation explicit in the thesis rather than hiding it behind a
single overall mean.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from method_portfolio_analysis import DEFAULT_INPUTS, _extract_per_video  # noqa: E402
from selector_significance import _normalize_metric_keys, _selector_results  # noqa: E402


METRICS = ("pk", "wd", "boundary_similarity", "f1_tol2")
METHODS = (
    ("BGE-divisive", "baseline"),
    ("Cross-model", "current"),
    ("Balanced selector", "selector"),
)


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def _load_manifest() -> dict[str, dict[str, Any]]:
    rows: dict[str, dict[str, Any]] = {}
    path = ROOT / "data" / "manifest.jsonl"
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            obj = json.loads(line)
            rows[str(obj["id"])] = obj
    return rows


def _load_portfolio(input_paths: list[Path]) -> dict[str, dict[str, dict[str, float]]]:
    portfolio: dict[str, dict[str, dict[str, float]]] = {}
    for path in input_paths:
        if not path.exists():
            continue
        for method, by_video in _extract_per_video(path).items():
            name = method if method not in portfolio else f"{path.stem}::{method}"
            portfolio[name] = by_video
    return portfolio


def _mean(rows: list[dict[str, float]]) -> dict[str, float]:
    return {
        metric: float(np.mean([row[metric] for row in rows if metric in row]))
        for metric in METRICS
    }


def _fmt(value: float) -> str:
    return f"{value:.4f}"


def _latex_escape(text: str) -> str:
    return text.replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


def _display_domain(domain: str) -> str:
    if domain.upper() == "CS":
        return "CS"
    return domain.title()


def _domain_rows(
    manifest: dict[str, dict[str, Any]],
    methods: dict[str, dict[str, dict[str, float]]],
) -> list[dict[str, Any]]:
    domains = sorted({str(row["domain"]) for row in manifest.values()})
    rows: list[dict[str, Any]] = []
    for domain in domains:
        video_ids = sorted([video_id for video_id, row in manifest.items() if row["domain"] == domain])
        row: dict[str, Any] = {
            "domain": domain,
            "n_videos": len(video_ids),
            "n_chapters": int(sum(int(manifest[v]["num_chapters"]) for v in video_ids)),
        }
        for _, key in METHODS:
            values = [methods[key][video_id] for video_id in video_ids if video_id in methods[key]]
            row[key] = _mean(values)
        row["selector_delta_pk_vs_baseline"] = row["selector"]["pk"] - row["baseline"]["pk"]
        row["selector_delta_wd_vs_baseline"] = row["selector"]["wd"] - row["baseline"]["wd"]
        row["selector_delta_pk_vs_current"] = row["selector"]["pk"] - row["current"]["pk"]
        row["selector_delta_wd_vs_current"] = row["selector"]["wd"] - row["current"]["wd"]
        rows.append(row)
    return rows


def build_report(
    input_paths: list[Path],
    selector_path: Path,
    selector_name: str,
    baseline_method: str,
    current_method: str,
) -> dict[str, Any]:
    manifest = _load_manifest()
    portfolio = _load_portfolio(input_paths)
    selector_abs = selector_path if selector_path.is_absolute() else ROOT / selector_path
    methods = {
        "baseline": {
            vid: _normalize_metric_keys(row)
            for vid, row in portfolio[baseline_method].items()
        },
        "current": {
            vid: _normalize_metric_keys(row)
            for vid, row in portfolio[current_method].items()
        },
        "selector": _selector_results(portfolio, selector_abs, selector_name),
    }
    rows = _domain_rows(manifest, methods)
    return {
        "meta": {
            "selector_file": str(selector_abs.relative_to(ROOT)),
            "selector_name": selector_name,
            "baseline_method": baseline_method,
            "current_method": current_method,
            "n_domains": len(rows),
            "n_videos": len(manifest),
        },
        "rows": rows,
    }


def _markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Domain Performance",
        "",
        "Generated by `python scripts/domain_performance_analysis.py`.",
        "",
        "| Domain | Videos | Chapters | Baseline Pk | Cross Pk | Selector Pk | Baseline WD | Cross WD | Selector WD |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in report["rows"]:
        lines.append(
            "| {domain} | {n_videos} | {n_chapters} | {bpk} | {cpk} | {spk} | {bwd} | {cwd} | {swd} |".format(
                domain=row["domain"],
                n_videos=row["n_videos"],
                n_chapters=row["n_chapters"],
                bpk=_fmt(row["baseline"]["pk"]),
                cpk=_fmt(row["current"]["pk"]),
                spk=_fmt(row["selector"]["pk"]),
                bwd=_fmt(row["baseline"]["wd"]),
                cwd=_fmt(row["current"]["wd"]),
                swd=_fmt(row["selector"]["wd"]),
            )
        )

    improved_baseline_pk = sum(1 for row in report["rows"] if row["selector_delta_pk_vs_baseline"] < 0)
    improved_baseline_wd = sum(1 for row in report["rows"] if row["selector_delta_wd_vs_baseline"] < 0)
    improved_current_pk = sum(1 for row in report["rows"] if row["selector_delta_pk_vs_current"] < 0)
    improved_current_wd = sum(1 for row in report["rows"] if row["selector_delta_wd_vs_current"] < 0)
    hardest = max(report["rows"], key=lambda row: row["selector"]["pk"])
    easiest = min(report["rows"], key=lambda row: row["selector"]["pk"])

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            f"- Selector improves Pk over baseline in {improved_baseline_pk}/{len(report['rows'])} domains.",
            f"- Selector improves WD over baseline in {improved_baseline_wd}/{len(report['rows'])} domains.",
            f"- Selector improves Pk over cross-model in {improved_current_pk}/{len(report['rows'])} domains.",
            f"- Selector improves WD over cross-model in {improved_current_wd}/{len(report['rows'])} domains.",
            f"- Lowest selector Pk domain: {easiest['domain']} ({_fmt(easiest['selector']['pk'])}).",
            f"- Highest selector Pk domain: {hardest['domain']} ({_fmt(hardest['selector']['pk'])}).",
            "",
        ]
    )
    return "\n".join(lines)


def _latex(report: dict[str, Any]) -> str:
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Domain-level Pk/WD for baseline, cross-model, and balanced selector.}",
        r"\label{tab:domain_performance}",
        r"\begin{tabular}{lrrrrrrrr}",
        r"\toprule",
        r"Domain & Videos & Chapters & Base Pk & Cross Pk & Sel. Pk & Base WD & Cross WD & Sel. WD \\",
        r"\midrule",
    ]
    for row in report["rows"]:
        lines.append(
            " & ".join(
                [
                    _latex_escape(_display_domain(row["domain"])),
                    str(row["n_videos"]),
                    str(row["n_chapters"]),
                    _fmt(row["baseline"]["pk"]),
                    _fmt(row["current"]["pk"]),
                    _fmt(row["selector"]["pk"]),
                    _fmt(row["baseline"]["wd"]),
                    _fmt(row["current"]["wd"]),
                    _fmt(row["selector"]["wd"]),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inputs", nargs="*", type=Path, default=DEFAULT_INPUTS)
    parser.add_argument("--selector", type=Path, default=ROOT / "results" / "method_selector_experiment_trainrank_balanced.json")
    parser.add_argument("--selector-name", default="extra")
    parser.add_argument("--baseline-method", default="divisive")
    parser.add_argument("--current-method", default="cross_e5_frac70_minlen11__align_contains_before")
    parser.add_argument("--output", type=Path, default=ROOT / "results" / "domain_performance_analysis.json")
    parser.add_argument("--docs-output", type=Path, default=ROOT / "docs" / "DOMAIN_PERFORMANCE.md")
    parser.add_argument("--tex-output", type=Path, default=ROOT / "thesis" / "tables" / "domain_performance.tex")
    args = parser.parse_args()

    report = build_report(args.inputs, args.selector, args.selector_name, args.baseline_method, args.current_method)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.docs_output.parent.mkdir(parents=True, exist_ok=True)
    args.tex_output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2), encoding="utf-8")
    args.docs_output.write_text(_markdown(report), encoding="utf-8")
    args.tex_output.write_text(_latex(report), encoding="utf-8")

    print(f"Wrote {args.output}")
    print(f"Wrote {args.docs_output}")
    print(f"Wrote {args.tex_output}")
    for row in report["rows"]:
        print(
            "{domain}: selector Pk={pk:.4f} WD={wd:.4f}".format(
                domain=row["domain"],
                pk=row["selector"]["pk"],
                wd=row["selector"]["wd"],
            )
        )


if __name__ == "__main__":
    main()
