"""Generate a scale-ratio positioning artifact for LECSEG."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
LECSEG_VIDEOS = 30


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def _latex_escape(text: str) -> str:
    return (
        text.replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
    )


def _ratio(videos: int) -> str:
    return f"{videos / LECSEG_VIDEOS:,.1f}x"


def _markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def _latex_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Low-resource scale positioning. Ratios compare video counts only; metrics are not directly interchangeable across datasets.}",
        r"\label{tab:low_resource_positioning}",
        r"\begin{tabularx}{\linewidth}{lrrX}",
        r"\toprule",
        " & ".join(_latex_escape(h) for h in headers) + r" \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(_latex_escape(cell) for cell in row) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabularx}", r"\end{table}"])
    return "\n".join(lines)


def build_rows() -> list[dict[str, Any]]:
    related = _read_json(ROOT / "results" / "related_work_comparison.json")
    by_work = {row["work"]: row for row in related["rows"]}

    external = [
        ("TreeSeg / TinyRec", 21, "Closest small unsupervised transcript comparator; not a scale advantage for LECSEG."),
        ("Chapter-Gen / multimodal video chapter generation", 9631, "Supervised multimodal chapter generation; over 300x LECSEG video count."),
        ("MiniSeg / YTSEG", 19299, "Supervised smart-chaptering benchmark; over 600x LECSEG video count."),
        ("AVLectures", 2350, "Large lecture-video representation resource; roughly 78x LECSEG video count."),
        ("VidChapters-7M", 817000, "Large-scale video chaptering benchmark; over 27,000x LECSEG video count."),
        ("Chapter-Llama", 10000, "Trained on about 10k videos and evaluated on 8.1k test videos."),
    ]

    rows = []
    for work, videos, interpretation in external:
        related_row = by_work.get(work, {})
        rows.append(
            {
                "work": work,
                "videos": videos,
                "ratio_vs_lecseg": _ratio(videos),
                "supervision": related_row.get("supervision", ""),
                "metric_context": related_row.get("reported_result", ""),
                "safe_interpretation": interpretation,
            }
        )
    return rows


def build_markdown(rows: list[dict[str, Any]]) -> str:
    headers = ["Work", "Videos", "Ratio vs LECSEG-30", "Supervision", "Safe interpretation"]
    table_rows = [
        [
            row["work"],
            f"{row['videos']:,}",
            row["ratio_vs_lecseg"],
            row["supervision"],
            row["safe_interpretation"],
        ]
        for row in rows
    ]
    return "\n".join(
        [
            "# Low-Resource Positioning",
            "",
            "Generated by `python scripts/generate_low_resource_positioning.py`.",
            "",
            "This artifact supports a narrow claim: LECSEG uses far fewer videos than large",
            "supervised chaptering systems while still providing a reproducible lecture-specific",
            "benchmark, local statistical tests, hierarchy, and error/oracle analysis. It does",
            "not support an external best-system claim because datasets and metrics differ.",
            "",
            _markdown_table(headers, table_rows),
            "",
            "## Safe Wording",
            "",
            "> LECSEG is not stronger than large supervised chaptering systems on external",
            "> benchmark performance. Its value is that a 30-video, lecture-specific,",
            "> reproducible benchmark still yields statistically supported local gains and",
            "> exposes the candidate-selection bottleneck at a tiny fraction of the scale.",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json-output", type=Path, default=ROOT / "results" / "low_resource_positioning.json")
    parser.add_argument("--docs-output", type=Path, default=ROOT / "docs" / "LOW_RESOURCE_POSITIONING.md")
    parser.add_argument("--tex-output", type=Path, default=ROOT / "thesis" / "tables" / "low_resource_positioning.tex")
    args = parser.parse_args()

    rows = build_rows()
    args.json_output.write_text(json.dumps({"lecseg_videos": LECSEG_VIDEOS, "rows": rows}, indent=2), encoding="utf-8")
    args.docs_output.write_text(build_markdown(rows), encoding="utf-8")

    headers = ["Work", "Videos", "Scale", "Interpretation"]
    latex_rows = [
        [
            row["work"].replace(" / multimodal video chapter generation", ""),
            f"{row['videos']:,}",
            row["ratio_vs_lecseg"],
            row["safe_interpretation"],
        ]
        for row in rows
    ]
    args.tex_output.parent.mkdir(parents=True, exist_ok=True)
    args.tex_output.write_text(_latex_table(headers, latex_rows), encoding="utf-8")

    print(f"Wrote {args.json_output}")
    print(f"Wrote {args.docs_output}")
    print(f"Wrote {args.tex_output}")


if __name__ == "__main__":
    main()
