"""Summarise balanced selector robustness across method-pool sizes."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
METRICS = ("pk", "wd", "boundary_similarity", "f1_tol2")


INPUTS = [
    ("k30", ROOT / "results" / "method_selector_experiment_trainrank_balanced_k30.json"),
    ("k50", ROOT / "results" / "method_selector_experiment_trainrank_balanced_k50.json"),
    ("k80", ROOT / "results" / "method_selector_experiment_trainrank_balanced.json"),
    ("k120", ROOT / "results" / "method_selector_experiment_trainrank_balanced_k120.json"),
]


def _read(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def _metric(row: dict[str, Any], key: str) -> float:
    if key in row:
        return float(row[key])
    if key == "f1_tol2":
        return float(row.get("f1_t2", row.get("f1", 0.0)))
    return float(row.get(key, 0.0))


def _metrics(row: dict[str, Any]) -> dict[str, float]:
    return {key: _metric(row, key) for key in METRICS}


def _fmt(value: float) -> str:
    return f"{value:.4f}"


def _latex_escape(text: str) -> str:
    return text.replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")


def build_report() -> dict[str, Any]:
    rows = []
    for label, path in INPUTS:
        data = _read(path)
        extra = data["selectors"]["extra"]["metrics"]
        rows.append(
            {
                "label": label,
                "top_k": int(data["meta"]["top_k"]),
                "source": str(path.relative_to(ROOT)),
                **_metrics(extra),
            }
        )

    best_pk = min(rows, key=lambda row: (row["pk"], row["wd"]))
    best_wd = min(rows, key=lambda row: (row["wd"], row["pk"]))
    best_balanced = min(rows, key=lambda row: ((row["pk"] + row["wd"]) / 2.0, row["pk"]))
    return {
        "meta": {
            "selector": "balanced ExtraTrees",
            "n_settings": len(rows),
            "metrics": list(METRICS),
        },
        "rows": rows,
        "best_pk": best_pk["label"],
        "best_wd": best_wd["label"],
        "best_balanced": best_balanced["label"],
    }


def _markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Selector Robustness",
        "",
        "Generated by `python scripts/selector_robustness_analysis.py`.",
        "",
        "| Setting | top_k | Pk | WD | BS | F1@2 | Source |",
        "| --- | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for row in report["rows"]:
        lines.append(
            "| {label} | {top_k} | {pk} | {wd} | {bs} | {f1} | `{source}` |".format(
                label=row["label"],
                top_k=row["top_k"],
                pk=_fmt(row["pk"]),
                wd=_fmt(row["wd"]),
                bs=_fmt(row["boundary_similarity"]),
                f1=_fmt(row["f1_tol2"]),
                source=row["source"],
            )
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            f"- Best Pk setting: {report['best_pk']}.",
            f"- Best WD setting: {report['best_wd']}.",
            f"- Best balanced Pk/WD setting: {report['best_balanced']}.",
            "- The result is not monotonic in pool size: too small a pool has little room "
            "to improve over the global method, while too large a pool adds unstable "
            "candidate methods.",
            "",
        ]
    )
    return "\n".join(lines)


def _latex(report: dict[str, Any]) -> str:
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Balanced selector robustness across candidate method-pool sizes.}",
        r"\label{tab:selector_robustness}",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"Setting & top-$k$ & Pk & WD & BS & F1@2 \\",
        r"\midrule",
    ]
    for row in report["rows"]:
        lines.append(
            " & ".join(
                [
                    _latex_escape(row["label"]),
                    str(row["top_k"]),
                    _fmt(row["pk"]),
                    _fmt(row["wd"]),
                    _fmt(row["boundary_similarity"]),
                    _fmt(row["f1_tol2"]),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "results" / "selector_robustness_analysis.json")
    parser.add_argument("--docs-output", type=Path, default=ROOT / "docs" / "SELECTOR_ROBUSTNESS.md")
    parser.add_argument("--tex-output", type=Path, default=ROOT / "thesis" / "tables" / "selector_robustness.tex")
    args = parser.parse_args()

    report = build_report()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.docs_output.parent.mkdir(parents=True, exist_ok=True)
    args.tex_output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2), encoding="utf-8")
    args.docs_output.write_text(_markdown(report), encoding="utf-8")
    args.tex_output.write_text(_latex(report), encoding="utf-8")

    best = next(row for row in report["rows"] if row["label"] == report["best_balanced"])
    print(f"Wrote {args.output}")
    print(f"Wrote {args.docs_output}")
    print(f"Wrote {args.tex_output}")
    print(
        "Best balanced setting: {label} Pk={pk:.4f} WD={wd:.4f} F1@2={f1_tol2:.4f}".format(
            **best
        )
    )


if __name__ == "__main__":
    main()
